// Annexe C of the official "Regulations for the FIFA World Cup 26" —
// the 495 possible combinations of which 8 of the 12 groups provide a
// qualifying (top-8) 3rd-place team, and which of those groups' 3rd-place
// team faces which group winner in the round of 32.
//
// Each entry is 8 characters, one per column, in the fixed column order
// below (the 8 R32 matches that pair a group winner against a "best 3rd
// place" team). The character is the source group letter for that match's
// 3rd-place opponent. E.g. row 1 = "EJIFHGLK" means: 1A plays the 3rd of
// group E, 1B plays the 3rd of J, 1D plays the 3rd of I, 1E plays the 3rd
// of F, 1G plays the 3rd of H, 1I plays the 3rd of G, 1K plays the 3rd of
// L, 1L plays the 3rd of K.

export const THIRD_PLACE_MATCH_SLOTS = ["1A", "1B", "1D", "1E", "1G", "1I", "1K", "1L"] as const;
export type ThirdPlaceMatchSlot = (typeof THIRD_PLACE_MATCH_SLOTS)[number];

export const THIRD_PLACE_COMBINATIONS: readonly string[] = [
  "EJIFHGLK", "HGIDJFLK", "EJIDHGLK", "EJIDHFLK", "EGIDJFLK",
  "EGJDHFLK", "EGIDHFLK", "EGJDHFLI", "EGJDHFIK", "HGICJFLK",
  "EJICHGLK", "EJICHFLK", "EGICJFLK", "EGJCHFLK", "EGICHFLK",
  "EGJCHFLI", "EGJCHFIK", "HGICJDLK", "CJIDHFLK", "CGIDJFLK",
  "CGJDHFLK", "CGIDHFLK", "CGJDHFLI", "CGJDHFIK", "EJICHDLK",
  "EGICJDLK", "EGJCHDLK", "EGICHDLK", "EGJCHDLI", "EGJCHDIK",
  "CJEDIFLK", "CJEDHFLK", "CEIDHFLK", "CJEDHFLI", "CJEDHFIK",
  "CGEDJFLK", "CGEDIFLK", "CGEDJFLI", "CGEDJFIK", "CGEDHFLK",
  "CGJDHFLE", "CGJDHFEK", "CGEDHFLI", "CGEDHFIK", "CGJDHFEI",
  "HJBFIGLK", "EJIBHGLK", "EJBFIHLK", "EJBFIGLK", "EJBFHGLK",
  "EGBFIHLK", "EJBFHGLI", "EJBFHGIK", "HJBDIGLK", "HJBDIFLK",
  "IGBDJFLK", "HGBDJFLK", "HGBDIFLK", "HGBDJFLI", "HGBDJFIK",
  "EJBDIHLK", "EJBDIGLK", "EJBDHGLK", "EGBDIHLK", "EJBDHGLI",
  "EJBDHGIK", "EJBDIFLK", "EJBDHFLK", "EIBDHFLK", "EJBDHFLI",
  "EJBDHFIK", "EGBDJFLK", "EGBDIFLK", "EGBDJFLI", "EGBDJFIK",
  "EGBDHFLK", "HGBDJFLE", "HGBDJFEK", "EGBDHFLI", "EGBDHFIK",
  "HGBDJFEI", "HJBCIGLK", "HJBCIFLK", "IGBCJFLK", "HGBCJFLK",
  "HGBCIFLK", "HGBCJFLI", "HGBCJFIK", "EJBCIHLK", "EJBCIGLK",
  "EJBCHGLK", "EGBCIHLK", "EJBCHGLI", "EJBCHGIK", "EJBCIFLK",
  "EJBCHFLK", "EIBCHFLK", "EJBCHFLI", "EJBCHFIK", "EGBCJFLK",
  "EGBCIFLK", "EGBCJFLI", "EGBCJFIK", "EGBCHFLK", "HGBCJFLE",
  "HGBCJFEK", "EGBCHFLI", "EGBCHFIK", "HGBCJFEI", "HJBCIDLK",
  "IGBCJDLK", "HGBCJDLK", "HGBCIDLK", "HGBCJDLI", "HGBCJDIK",
  "CJBDIFLK", "CJBDHFLK", "CIBDHFLK", "CJBDHFLI", "CJBDHFIK",
  "CGBDJFLK", "CGBDIFLK", "CGBDJFLI", "CGBDJFIK", "CGBDHFLK",
  "CGBDHFLJ", "HGBCJFDK", "CGBDHFLI", "CGBDHFIK", "HGBCJFDI",
  "EJBCIDLK", "EJBCHDLK", "EIBCHDLK", "EJBCHDLI", "EJBCHDIK",
  "EGBCJDLK", "EGBCIDLK", "EGBCJDLI", "EGBCJDIK", "EGBCHDLK",
  "HGBCJDLE", "HGBCJDEK", "EGBCHDLI", "EGBCHDIK", "HGBCJDEI",
  "CJBDEFLK", "CEBDIFLK", "CJBDEFLI", "CJBDEFIK", "CEBDHFLK",
  "CJBDHFLE", "CJBDHFEK", "CEBDHFLI", "CEBDHFIK", "CJBDHFEI",
  "CGBDEFLK", "CGBDJFLE", "CGBDJFEK", "CGBDEFLI", "CGBDEFIK",
  "CGBDJFEI", "CGBDHFLE", "CGBDHFEK", "HGBCJFDE", "CGBDHFEI",
  "HJIFAGLK", "EJIAHGLK", "EJIFAHLK", "EJIFAGLK", "EGJFAHLK",
  "EGIFAHLK", "EGJFAHLI", "EGJFAHIK", "HJIDAGLK", "HJIDAFLK",
  "IGJDAFLK", "HGJDAFLK", "HGIDAFLK", "HGJDAFLI", "HGJDAFIK",
  "EJIDAHLK", "EJIDAGLK", "EGJDAHLK", "EGIDAHLK", "EGJDAHLI",
  "EGJDAHIK", "EJIDAFLK", "HJEDAFLK", "HEIDAFLK", "HJEDAFLI",
  "HJEDAFIK", "EGJDAFLK", "EGIDAFLK", "EGJDAFLI", "EGJDAFIK",
  "HGEDAFLK", "HGJDAFLE", "HGJDAFEK", "HGEDAFLI", "HGEDAFIK",
  "HGJDAFEI", "HJICAGLK", "HJICAFLK", "IGJCAFLK", "HGJCAFLK",
  "HGICAFLK", "HGJCAFLI", "HGJCAFIK", "EJICAHLK", "EJICAGLK",
  "EGJCAHLK", "EGICAHLK", "EGJCAHLI", "EGJCAHIK", "EJICAFLK",
  "HJECAFLK", "HEICAFLK", "HJECAFLI", "HJECAFIK", "EGJCAFLK",
  "EGICAFLK", "EGJCAFLI", "EGJCAFIK", "HGECAFLK", "HGJCAFLE",
  "HGJCAFEK", "HGECAFLI", "HGECAFIK", "HGJCAFEI", "HJICADLK",
  "IGJCADLK", "HGJCADLK", "HGICADLK", "HGJCADLI", "HGJCADIK",
  "CJIDAFLK", "HJFCADLK", "HFICADLK", "HJFCADLI", "HJFCADIK",
  "CGJDAFLK", "CGIDAFLK", "CGJDAFLI", "CGJDAFIK", "HGFCADLK",
  "CGJDAFLH", "HGJCAFDK", "HGFCADLI", "HGFCADIK", "HGJCAFDI",
  "EJICADLK", "HJECADLK", "HEICADLK", "HJECADLI", "HJECADIK",
  "EGJCADLK", "EGICADLK", "EGJCADLI", "EGJCADIK", "HGECADLK",
  "HGJCADLE", "HGJCADEK", "HGECADLI", "HGECADIK", "HGJCADEI",
  "CJEDAFLK", "CEIDAFLK", "CJEDAFLI", "CJEDAFIK", "HEFCADLK",
  "HJFCADLE", "HJECAFDK", "HEFCADLI", "HEFCADIK", "HJECAFDI",
  "CGEDAFLK", "CGJDAFLE", "CGJDAFEK", "CGEDAFLI", "CGEDAFIK",
  "CGJDAFEI", "HGFCADLE", "HGECAFDK", "HGJCAFDE", "HGECAFDI",
  "HJBAIGLK", "HJBAIFLK", "IJBFAGLK", "HJBFAGLK", "HGBAIFLK",
  "HJBFAGLI", "HJBFAGIK", "EJBAIHLK", "EJBAIGLK", "EJBAHGLK",
  "EGBAIHLK", "EJBAHGLI", "EJBAHGIK", "EJBAIFLK", "EJBFAHLK",
  "EIBFAHLK", "EJBFAHLI", "EJBFAHIK", "EJBFAGLK", "EGBAIFLK",
  "EJBFAGLI", "EJBFAGIK", "EGBFAHLK", "HJBFAGLE", "HJBFAGEK",
  "EGBFAHLI", "EGBFAHIK", "HJBFAGEI", "IJBDAHLK", "IJBDAGLK",
  "HJBDAGLK", "IGBDAHLK", "HJBDAGLI", "HJBDAGIK", "IJBDAFLK",
  "HJBDAFLK", "HIBDAFLK", "HJBDAFLI", "HJBDAFIK", "FJBDAGLK",
  "IGBDAFLK", "FJBDAGLI", "FJBDAGIK", "HGBDAFLK", "HGBDAFLJ",
  "HGBDAFJK", "HGBDAFLI", "HGBDAFIK", "HGBDAFIJ", "EJBAIDLK",
  "EJBDAHLK", "EIBDAHLK", "EJBDAHLI", "EJBDAHIK", "EJBDAGLK",
  "EGBAIDLK", "EJBDAGLI", "EJBDAGIK", "EGBDAHLK", "HJBDAGLE",
  "HJBDAGEK", "EGBDAHLI", "EGBDAHIK", "HJBDAGEI", "EJBDAFLK",
  "EIBDAFLK", "EJBDAFLI", "EJBDAFIK", "HEBDAFLK", "HJBDAFLE",
  "HJBDAFEK", "HEBDAFLI", "HEBDAFIK", "HJBDAFEI", "EGBDAFLK",
  "EGBDAFLJ", "EGBDAFJK", "EGBDAFLI", "EGBDAFIK", "EGBDAFIJ",
  "HGBDAFLE", "HGBDAFEK", "HGBDAFEJ", "HGBDAFEI", "IJBCAHLK",
  "IJBCAGLK", "HJBCAGLK", "IGBCAHLK", "HJBCAGLI", "HJBCAGIK",
  "IJBCAFLK", "HJBCAFLK", "HIBCAFLK", "HJBCAFLI", "HJBCAFIK",
  "CJBFAGLK", "IGBCAFLK", "CJBFAGLI", "CJBFAGIK", "HGBCAFLK",
  "HGBCAFLJ", "HGBCAFJK", "HGBCAFLI", "HGBCAFIK", "HGBCAFIJ",
  "EJBAICLK", "EJBCAHLK", "EIBCAHLK", "EJBCAHLI", "EJBCAHIK",
  "EJBCAGLK", "EGBAICLK", "EJBCAGLI", "EJBCAGIK", "EGBCAHLK",
  "HJBCAGLE", "HJBCAGEK", "EGBCAHLI", "EGBCAHIK", "HJBCAGEI",
  "EJBCAFLK", "EIBCAFLK", "EJBCAFLI", "EJBCAFIK", "HEBCAFLK",
  "HJBCAFLE", "HJBCAFEK", "HEBCAFLI", "HEBCAFIK", "HJBCAFEI",
  "EGBCAFLK", "EGBCAFLJ", "EGBCAFJK", "EGBCAFLI", "EGBCAFIK",
  "EGBCAFIJ", "HGBCAFLE", "HGBCAFEK", "HGBCAFEJ", "HGBCAFEI",
  "IJBCADLK", "HJBCADLK", "HIBCADLK", "HJBCADLI", "HJBCADIK",
  "CJBDAGLK", "IGBCADLK", "CJBDAGLI", "CJBDAGIK", "HGBCADLK",
  "HGBCADLJ", "HGBCADJK", "HGBCADLI", "HGBCADIK", "HGBCADIJ",
  "CJBDAFLK", "CIBDAFLK", "CJBDAFLI", "CJBDAFIK", "HFBCADLK",
  "CJBDAFLH", "HJBCAFDK", "HFBCADLI", "HFBCADIK", "HJBCAFDI",
  "CGBDAFLK", "CGBDAFLJ", "CGBDAFJK", "CGBDAFLI", "CGBDAFIK",
  "CGBDAFIJ", "CGBDAFLH", "HGBCAFDK", "HGBCAFDJ", "HGBCAFDI",
  "EJBCADLK", "EIBCADLK", "EJBCADLI", "EJBCADIK", "HEBCADLK",
  "HJBCADLE", "HJBCADEK", "HEBCADLI", "HEBCADIK", "HJBCADEI",
  "EGBCADLK", "EGBCADLJ", "EGBCADJK", "EGBCADLI", "EGBCADIK",
  "EGBCADIJ", "HGBCADLE", "HGBCADEK", "HGBCADEJ", "HGBCADEI",
  "CEBDAFLK", "CJBDAFLE", "CJBDAFEK", "CEBDAFLI", "CEBDAFIK",
  "CJBDAFEI", "HFBCADLE", "HEBCAFDK", "HJBCAFDE", "HEBCAFDI",
  "CGBDAFLE", "CGBDAFEK", "CGBDAFEJ", "CGBDAFEI", "HGBCAFDE",
];

/**
 * Resolves, for a given set of 8 qualified third-place groups, which
 * group's third-place team is the opponent for each of the 8 R32 matches
 * that need a "best 3rd place" team — per Annexe C of the regulations.
 * Returns null if the combination doesn't match any of the 495 rows
 * (e.g. fewer/more than 8 groups passed in).
 */
export function resolveThirdPlaceOpponents(
  qualifiedThirdPlaceGroups: readonly string[]
): Record<ThirdPlaceMatchSlot, string> | null {
  const target = [...qualifiedThirdPlaceGroups].sort().join("");

  const row = THIRD_PLACE_COMBINATIONS.find(
    (combo) => [...combo].sort().join("") === target
  );
  if (!row) return null;

  return THIRD_PLACE_MATCH_SLOTS.reduce((acc, slot, i) => {
    acc[slot] = row[i];
    return acc;
  }, {} as Record<ThirdPlaceMatchSlot, string>);
}
